### ISSUE TITLE
Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by androidneha** [ashvin27/react-datatable#10]
Check the render method of `ReactDatatable`. See https://fb.me/react-warning-keys for more information.
###
in tr (created by ReactDatatable)
    in ReactDatatable (at Users.js:140)
    in div (at Users.js:137)
    in div (at Users.js:136)
    in div (at Users.js:134)
    in div (at Users.js:132)
    in Users (created by ConnectFunction)
    in ConnectFunction (at PrivateRoute.js:11)
    in Route (at PrivateRoute.js:7)
    in PrivateRoute (created by ConnectFunction)
    in ConnectFunction (at App.js:46)
    in Switch (at App.js:44)
    in Switch (at App.js:40)
    in div (at App.js:39)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:38)
    in Provider (at App.js:37)
    in App (at src/index.js:7)

Because of this error search, pagination, sorting not working Kindly help me out

**Comment by ashvin27** [comment]
Please add id as a key in your record collection.
Please refer example below:
**[
  {
    "id": "55f14312c7447c3da7051b26",
    "address": "228 City Road",
    "address line 2": "Cardiff",
    "name": ".CN Chinese"
  },
  {
    "id": "55f14312c7447c3da7051b27",
    "address": "376 Rayleigh Road",
    "address line 2": "Essex",
    "name": "@ Thai"
  }
]**

**Comment by androidneha** [comment]
but I have _id in my table as per mongo db so my record is like
[
{
"_id": "55f14312c7447c3da7051b26",
"address": "228 City Road",
"address line 2": "Cardiff",
"name": ".CN Chinese"
},
{
"_id": "55f14312c7447c3da7051b27",
"address": "376 Rayleigh Road",
"address line 2": "Essex",
"name": "@ Thai"
}
]

**Comment by ashvin27** [comment]
Yes, but the plugin does not understand _id, its required id for every record.

**Comment by androidneha** [comment]
Please update your library asap because mongo support _id not id so your library is not compatible with a feature rich MERN application.

**Comment by pakcybershagufta** [comment]
Add 
key_column: 'unique_id'
in config object

**Comment by pakcybershagufta** [comment]
this.config = {
      page_size: 20,
      length_menu: [20, 40, 60],
      show_filter: true,
      show_first: true,
      show_pagination: true,
      key_column: 'booking_id',
      button: {
        excel: false,
        print: false,
      },
    };
