### ISSUE TITLE
[Request] Is it possible override html nodes for multilanguage or change icons?

### ISSUE THREAD

**Issue by emehmet** [ashvin27/react-datatable#13]
Hi,

Thanks for very very easy use datatable component. Great job.

Is it possible override html nodes for multilanguage or change icons?

And I guess there is a problem excel export. Exported excel file is 2kb around and can't be opened.

**Comment by ashvin27** [comment]
Hello,

You can change icons by overriding css of **asc** **desc** class

**Comment by ashvin27** [comment]
You can provide column text in any language you want.

**Comment by ashvin27** [comment]
I'm closing the issue, still you getting same issue.

**Comment by emehmet** [comment]
Thanks. I did as you said.
