### ISSUE TITLE
Bug on CSS

### ISSUE THREAD

**Issue by jefri55** [ashvin27/react-datatable#14]
`./node_modules/@ashvin27/react-datatable/lib/style.css 1:12
Module parse failed: Unexpected token (1:12)
You may need an appropriate loader to handle this file type.
> th.sortable {
|     color: #2196F3;
|     cursor: pointer;`

**Comment by ashvin27** [comment]
Please use "style-loader" and "css-loader" in webpack config file.

**Comment by aiveneh** [comment]
I have been tackling this same issue for a while now.
I have style-loader and css-loaders in my Webpack config, it works well on the server but crashes on the server (I have SSR setup),

The problem being that Node can't parse css, and it looks like the css-loaders and style-loaders are not kicking in on the server side.

Is there any way I could work around it , I have tried removing your `require('./style.css');`, but that isn't a scalable solution

**Comment by aiveneh** [comment]
I finally found a solution to my issue, apparently I needed to ensure that I provided Webpack with the vendor code on the server by specifying it under `nodeExternals`

**Comment by ashvin27** [comment]
I'm closing this issue. Reopen it again if still anyone is facing the issue.
