### ISSUE TITLE
Nested

### ISSUE THREAD

**Issue by Ericokim** [ashvin27/react-datatable#20]
Hi can't  read some nested data from my json file. please help

**Comment by ashvin27** [comment]
@Ericokim can you please share detail about what is the issue you getting.

**Comment by Ericokim** [comment]
I can't capture the data i have in mongodb if its in nested form in your table records={data:{data}}

**Comment by mkikets99** [comment]
> records={data:{data}}

I dont know? but it can be because of this
if your `var data` is array you can pass like this: `records={this.data}`

If no i can try to help you with your problem

**Comment by abhi4pr** [comment]
How can i access firstname ?

[
                {
                    "id": 1,
                    "name": "dada",
                    "address": "165 galaxy",
                    "customer": {
                        "ownerid": 1,
                        "firstname": "John",
                        "lastname": "Johnson"
                    }
                },
                {
                    "id": 2,
                    "name": "daddddd",
                    "address": "3.2 tejaji nagar",
                    "customer": {
                        "ownerid": 2,
                        "firstname": "david",
                        "lastname": "carter"
                    }
                }
            ]

**Comment by abhi4pr** [comment]
How can i access firstname [data from nested json objects]???

![-New-document-20-JSON-Editor-Online-view-edit-and-format-JSON-online](https://user-images.githubusercontent.com/29729513/121863449-7d993080-cd19-11eb-9e8a-7f67ae6f2c07.png)

**Comment by mkikets99** [comment]
> How can i access firstname [data from nested json objects]???
> 
> ![-New-document-20-JSON-Editor-Online-view-edit-and-format-JSON-online](https://user-images.githubusercontent.com/29729513/121863449-7d993080-cd19-11eb-9e8a-7f67ae6f2c07.png)

what is the point of doing that?
You need something like this?:
| FName        | LName           | Address  |
| ------------ |:-------------:| -----:|
| John      | Johnson | 165 galaxy |
| ...      | ...      |   ... |

**Comment by HarmNullix** [comment]
See #80
