### ISSUE TITLE
Failed to Compile

### ISSUE THREAD

**Issue by genevieveEP** [ashvin27/react-datatable#21]
./node_modules/@ashvin27/react-datatable/lib/up-arrow.png 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

**Comment by ashvin27** [comment]
Hello,

Need to add appropriate loader into your webpack config file.

Try below example.

{
    test: /\.(png|jpg|gif)$/i,
    use: {
        loader: 'url-loader',
        options: {}
    }
}

**Comment by shvagen** [comment]
I had the same issue and that fixed it. Thanks!

**Comment by ashvin27** [comment]
I'm closing this issue if anyone got this issue again they can reopen it.
