### ISSUE TITLE
No example for Server-side pagination

### ISSUE THREAD

**Issue by giriannamalai** [ashvin27/react-datatable#24]
Hi,
The library is nice. Easy to integrate. But could not find the server-side example of the implementation.
Please add it in the documentation.

**Comment by ashvin27** [comment]
When you enable server side data then you need to implement **onChange** method of table it will call on table actions(page change, sorting, filtering, page length change) etc.

**Comment by a8c71** [comment]
Got it, Thank you!

**Comment by Deewai** [comment]
@a8c71 Could you please provide an example of the server-side rendering?

**Comment by ashvin27** [comment]
Yes, of course, we are working on detailed examples. We will release that soon

**Comment by ashvin27** [comment]
A complete example guide is live now follow link: http://react-datatable.in/
