### ISSUE TITLE
Conflicts with the bootstrap4.min.css/js

### ISSUE THREAD

**Issue by ekibet-dev** [ashvin27/react-datatable#25]
Hello, The package is awesome though if using bootstrap js and css does not display properly. For more contact back.

**Comment by ashvin27** [comment]
Hello,

Thanks or using it.

Can you please share exact problem what you get while using plugin.
Share some screenshots or sample code.




Thanks & Regard
Ashvin Patel

**Comment by ekibet666** [comment]
Hello,
Thanks for responding. Can i share screen via skype or any other platform?

Thanks,
EVANS

**Comment by ashvin27** [comment]
Hello,

Yes you can share screen but i will be available at 9:00 PM IST for Skype
call, or you can suggest your preferred time.




Thanks & Regard
Ashvin Patel

**Comment by ekibet666** [comment]
Hello,

I am also available at 11;00pm IST.

Thanks

**Comment by ekibet666** [comment]
Hello,
At what time are you available? i need some clarification if custom
pagination is supported by your react js npm package?
If so, we can connect via skype.

Thanks & Regards
Evans

**Comment by ashvin27** [comment]
Hello,

Are you available tomorrow for the Skype call.

**Comment by ekibet666** [comment]
At what time kindly?

**Comment by ekibet666** [comment]
Hello,
Any help based on this provided npm library>

Thanks,
EVANS

**Comment by ashvin27** [comment]
Hello,
for help you need to share sample code or any way how do we reproduce the issue.

**Comment by ekibet666** [comment]
Hello,
Does react-datatable supports server and client side paginations. for
instance, i want to fetch chucks of the data from the server..
Kindly treat this as a matter of agency.

Thanks,
EVANS

**Comment by ekibet666** [comment]
Or lets have a call via skype
My Skype ID: evanskibet114_1
Thanks,

**Comment by ashvin27** [comment]
Yes it is support client and server side pagination.

Check documentation for more detail.




Thanks & Regard
Ashvin Patel

**Comment by ekibet666** [comment]
Hello Ashvin,
I can't find an example in the documentation, can we have a call via skype
kindly

Thanks,
EVANS

**Comment by ekibet666** [comment]
Can we have a call to confirm the issue with my pagination using your
react-datatable?

Thanks
EVANS

**Comment by ashvin27** [comment]
Yes sure.




Thanks & Regard
Ashvin Patel

**Comment by ekibet666** [comment]
Yes can we have a call Kindly,

Thanks
EVANS

**Comment by ashvin27** [comment]
We can do a skype call.

Today I'm available after 9:30pm IST for the skype call.

Please suggest when you will be available.




Thanks & Regard
Ashvin Patel

**Comment by ekibet666** [comment]
I am currently available..
My Skype ID: evanskibet114_1
Thanks,
EVANS
