### ISSUE TITLE
Export to Excel functionality is broken - file cannot be opened

### ISSUE THREAD

**Issue by shvagen** [ashvin27/react-datatable#28]
When exporting to excel the actual download works, however the file is not openable. 

![image](https://user-images.githubusercontent.com/8887122/72086939-5f7e0400-32cd-11ea-965a-370938d21580.png)

**Comment by ashvin27** [comment]
Can you please share some more detail about the issue.

**Comment by Vipul25** [comment]
Getting the same issue that the File is not format or extension is not valid. changed the File Format from XLSX to XLS it is then opening with a warning.

**Comment by ashvin27** [comment]
New version (1.3.0) is available now with this fix.
Still it is exists then please reopen it again.
