### ISSUE TITLE
Unable to display IMAGE within table rows

### ISSUE THREAD

**Issue by ravidsp** [ashvin27/react-datatable#29]

**Comment by ashvin27** [comment]
Please share more information about what you want.

**Comment by aiveneh** [comment]
`{
        key: "avatar",
        text: "Avatar",
        width: 70,
        sortable: false,
        cell: record => {
          return (
            <img
              className="image css-img-object"
              src={
                record.avatar
                  ? record.avatar
                  : "/assets/img/default.png"
              }
              style={{
                width: "30px",
                height: "30px",
                borderRadius: "50%",
                marginRight: "10px"
              }}
            />
          );
        }
      },`

This is how I render images in the table

**Comment by ashvin27** [comment]
What is the error you got while using the above code?

**Comment by ashvin27** [comment]
Can you please provide detail?

**Comment by ashvin27** [comment]
I'm closing this issue now.
if anyone will face this issue again they can reopen it.
