### ISSUE TITLE
Dealing The Big Data or paginate call

### ISSUE THREAD

**Issue by firepmi** [ashvin27/react-datatable#34]
when we need to deal any big data, we call api for paginate.
like apicall?start_at=20&limitation=10

To use this plugin, I should load the whole data and load them at a once.
it make me to feel the website so slow.
Is there any way to call api for paginate?

**Comment by ashvin27** [comment]
Thanks for feedback.

There is a option for server side data with pagination. Please visit below links for example:
http://react-datatable.in/server-side-data.html
http://react-datatable.in/pagination-default.html

**Comment by firepmi** [comment]
It is required download the whole data at least once.
is there any option to set total count of the record data?

**Comment by ashvin27** [comment]
Yes, there is an option to set total counts for records.
You can use **total_record** prop.
These props will used to specify the total records in case of table data on is server-side.

You can also check the example of server-side data on below link:
http://react-datatable.in/server-side-data.html

Goto link and check source of example for more details.

**Comment by ashvin27** [comment]
Hello
Is this useful, can I close this issue.

**Comment by ashvin27** [comment]
Currently I'm closing this issue.
You can reopen it again if anyone will face this issue.
