### ISSUE TITLE
React Javascript Warning

### ISSUE THREAD

**Issue by emehmet** [ashvin27/react-datatable#36]
Hello,
Some functions gives an warning because of React's Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:void(0);

Thanks for great job.

**Comment by ashvin27** [comment]
Thanks for the feedback and suggestion.
We will fix it in next release.

**Comment by ashvin27** [comment]
Fixed in version 1.5.0
