### ISSUE TITLE
custom onSort function needed

### ISSUE THREAD

**Issue by Way-U-Need** [ashvin27/react-datatable#38]
Hey for the custom cell data I need custom onSort function to be manipulated
![screenshot-localhost_8080-2020 04 21-17_35_36](https://user-images.githubusercontent.com/43028741/79864157-9bf5eb80-83f6-11ea-8859-519641e6eb98.png) for table like this

**Comment by ashvin27** [comment]
thanks for feedback we add this feature in future releases

**Comment by ashvin27** [comment]
Fixed in version 1.5.0
