### ISSUE TITLE
Support for Functional Components

### ISSUE THREAD

**Issue by ashfaq92** [ashvin27/react-datatable#62]
Hi, thanks for the nice package. 
Can this package be used with functional components? because I could not see an example in your docs. If it supports functional components, please update the docs

**Comment by mkikets99** [comment]
I think you can...
Because this plugin is like DOM-element so you can just do this:
```javascript
import ReactDatatable from "@ashivin27/react-datatable";
//...
export default function example(props){
// Some actions with states, events and data
return (
<div>
<ReactDatatable config={config} records={records} columns={columns} />
</div>
}
```
This is just example of how ReactDatatable used... It is simply DOM
Hope this helps
If you have more questions, reply here

**Comment by ashvin27** [comment]
@ashfaq92 Is this helpful?
