### ISSUE TITLE
How to get data from nested json objects

### ISSUE THREAD

**Issue by abhi4pr** [ashvin27/react-datatable#80]
How can i access firstname [data from nested json objects]???

![-New-document-20-JSON-Editor-Online-view-edit-and-format-JSON-online](https://user-images.githubusercontent.com/29729513/121863687-bcc78180-cd19-11eb-8306-24b670556d5e.png)

**Comment by mkikets99** [comment]
> How can i access firstname [data from nested json objects]???
> 
> ![-New-document-20-JSON-Editor-Online-view-edit-and-format-JSON-online](https://user-images.githubusercontent.com/29729513/121863449-7d993080-cd19-11eb-9e8a-7f67ae6f2c07.png)

what is the point of doing that?
You need something like this?:
| FName        | LName           | Address  |
| ------------ |:-------------:| -----:|
| John      | Johnson | 165 galaxy |
| ...      | ...      |   ... |

**Comment by HarmNullix** [comment]
use this as column:

```
{
    key: "customer.firstname",
    text: "First Name",
    cell: (record) => record.customer.firstname
}
```
