### ISSUE TITLE
Rendering nested column data

### ISSUE THREAD

**Issue by vinodkurra** [ashvin27/react-datatable#9]
When I am trying to render nested data, How should I need to provide "KEY" name ?

Example : If I have below data, How can I print name in single column ?

let data = [
    {
       id: 1,
       userDetails : {
                 name : "vinod",
                 age : 23
               }
       }

  {
      id: 1,
      userDetails : {
                name : "kumar",
                age : 22
              }
     }

]

**Comment by ujjalacharya** [comment]
did you find solution to this problem ?

**Comment by Ericokim** [comment]
did you?

**Comment by Ericokim** [comment]
SOLVED!!!!!!!!!!!!!!!!!!!!

Hey use this as an example. Call the (cell option) function. BUT there just one hick up that you will face,that is the sort function won't work

 {
        key: "name",
        text: "Artist",
        width: 160,
        align: "left",
        sortable: true,
        cell: record => {
          return <Fragment>{record.artist.name}</Fragment>;
        }
      },

**Comment by ashvin27** [comment]
@Ericokim can you please provide more detail about **"BUT there just one hick up that you will face,that is the sort function won't work"**

**Comment by ashvin27** [comment]
now custom sort function prop is available in version 1.5.0 to sort data in any way.
